spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    connect-retries: 10
    connect-retries-interval: 2
    placeholders:
      exercise_insert_alias: "AS new"
      exercise_name_upsert: "new.exercise_name"
      exercise_muscle_group_upsert: "new.muscle_group"
      exercise_intensity_level_upsert: "new.intensity_level"
      food_insert_alias: "AS new"
      food_name_upsert: "new.name"
      food_unit_upsert: "new.unit"
      food_kcal100_upsert: "new.kcal100"
      food_protein100_upsert: "new.protein100"
      food_fat100_upsert: "new.fat100"
      food_carbs100_upsert: "new.carbs100"

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework: warn
